### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by mark-bradshaw** [terebentina/react-popover#3]
You've got a great component here. :)  It deserves to be published so people find it easier, and have an easier install path.  Go for it!

**Comment by terebentina** [comment]
It's already published on npm but with a namespace. Currently npm doesn't show search results from namespaced modules, that's why you don't find it. They say they will show these too...eventually. Until then I agree, it's less discoverable than it could be but I don't think renaming to `react-popover-the-sixth` is that much better.
How did you find it?

**Comment by mark-bradshaw** [comment]
Just a google search.  I've looked over some other implementations and in general I like yours a lot.  Much better than the one published as `react-popover`.  What about a rename to `react-pop`?

**Comment by terebentina** [comment]
Neah, I am ok waiting till npm manages to make namespaces searchable. Meanwhile word of mouth and google should do ;)
